name: Build and Release Maven Package

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean package --batch-mode

      - name: Increment version and tag
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=$(echo $VERSION | awk -F. '{OFS="."; $NF+=1; print $0}')
          mvn versions:set -DnewVersion=$NEW_VERSION
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Release $NEW_VERSION"
          git tag v$NEW_VERSION
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Push changes and tags
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
